spring.application.name=testetecnico

spring.datasource.url=jdbc:postgresql://localhost:5432/testetecnico
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

jwt.secret=5a2aafcacb9828e41fb7c8f8098952638645874b3a8ca45d2523fb2d5fc7166d
jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG